name: Check compilation

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "ga-ignore-**"

env:
  EXECUTABLES: "42sh"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest

    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build project
        timeout-minutes: 2
        run: |
          make && make clean

      - run: |
          for EXECUTABLE in $(echo $EXECUTABLES | tr "," "\n"); do
            if [[ ! -f $EXECUTABLE ]]; then
                echo "::error title=Executable not found $EXECUTABLE::"
                exit 1
            fi
          done
