name: Functionnal tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TEST_FILE: "./bonus/tests.json"

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest

    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build project
        timeout-minutes: 2
        run: |
          make && make clean

      - name: Run tests
        timeout-minutes: 1
        run: |
          ./bonus/tester.py --file $TEST_FILE
