name: Push mirror

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-PSU-200-PAR-2-1-42sh-martin.saldinger.git"
  MIRROR_URL_IT: "git@github.com:EpitechPromo2027/B-PSU-200-PAR-2-2-42sh-lou.onezime.git"

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.KEY }}

  push_to_mirror_it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL_IT }}
          ssh_private_key: ${{ secrets.KEY_LOU }}
